apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: game-server
    newName: harbor.dataknife.net/library/windrose-server-k8s
    newTag: latest
