---
name: Security

on:
  pull_request: null
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  container-scanning:
    uses: DataKnifeAI/github-workflows/.github/workflows/reusable-game-server-security.yml@v1
    secrets: inherit
    with:
      dockerfile: Dockerfile

  container-scanning-staging:
    uses: DataKnifeAI/github-workflows/.github/workflows/reusable-game-server-security.yml@v1
    secrets: inherit
    with:
      dockerfile: Dockerfile.staging
